tunnel: REPLACE_WITH_TUNNEL_UUID
credentials-file: /home/ubuntu/.cloudflared/REPLACE_WITH_TUNNEL_UUID.json

ingress:
  - hostname: worker.germanospina.com
    service: http://localhost:4001
    originRequest:
      connectTimeout: 30s
      noTLSVerify: true
  - service: http_status:404
